revision_v2/mysite/food/urls.py
from . import views
from django.urls import path

app_name = "food"

urlpatterns = [
   path('',views.IndexClassView.as_view(),name="index"),
   #/food/1
   path('<int:item_id>/',views.detail,name="detail"),
   path("item/",views.item,name="item"),
   #add
   path("add",views.create_item,name="create_item"),
   #edit
   path("update/<int:id>/",views.update_item,name="update_item"),
   #delete
   path("delete/<int:id>/",views.delete_item,name="delete_item")
]

revision_v2/mysite/food/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Item(models.Model):

   def __str__(self):
      return self.item_name
   user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
   item_name= models.CharField(max_length=200)
   item_desc= models.CharField(max_length=400)
   item_price= models.IntegerField()

revision_v2/mysite/food/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
   class Meta:
      model=Item
      fields=["item_name", "item_desc", "item_price"]

revision_v2/mysite/food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView 


# Create your views here.
def index(request):
   item_list = Item.objects.all();
   context={
      "item_list":item_list,
   }
   return render(request,'food/index.html',context)


class IndexClassView(ListView):
   model=Item
   template_name= "food/index.html"
   context_object_name="item_list"


def item(request):
   return HttpResponse("<h1>this is item view</h1>")

def detail(request,item_id):
   item = Item.objects.get(pk=item_id);
   context={
      "item":item,
   }
   return render(request,'food/detail.html',context)


def create_item(request):
   form = ItemForm(request.POST or None)

   if form.is_valid():
      item = form.save(commit=False)
      item.user_name = request.user
      item.save()
      return redirect("food:index")
   
   return render(request,'food/item-form.html',{'form':form})


def update_item(request,id):
   item= Item.objects.get(id=id)
   form= ItemForm(request.POST or None,instance=item)
   if form.is_valid():
      form.save()
      return redirect("food:index")

   return render(request,'food/item-form.html',{'form':form, 'item':item})

def delete_item(request,id):
   item= Item.objects.get(id=id)
   if request.method == 'POST':
      item.delete()
      return redirect("food:index")
   return render(request,'food/item-delete.html',{'item':item})

revision_v2/mysite/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'food:create_item' %}">add</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'profile' %}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" aria-disabled="true">Disabled</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% if messages %} {% for message in messages %} {{ message }} {% endfor %}
    {% endif %}
    {% if user.is_authenticated %}
      <form method="POST" action="{% url 'logout' %}">
        {% csrf_token %}
        <button type="submit">Logout</button>
      </form>
    {% else %}
      <a href="{% url 'login'  %}"">Login</a>
    {% endif %}
    {% block body %} {% endblock %}
  </body>
</html>

revision_v2/mysite/food/templates/food/detail.html
{% extends 'food/base.html' %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {% block body %}
    <div>{{item.item_name}}</div>
    <div>{{item.item_desc}}</div>
    <div>{{item.item_price}}</div>
    <a href="{% url 'food:delete_item' item.id %}">delete</a>
    {% endblock %}
  </body>
</html>

revision_v2/mysite/food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Document</title>
  </head>
  <body>
    {% block body %}
    <ul>
      {% for item in item_list %}
      <li>{{ item.id }} -- {{item.item_name }} -- {{ item.user_name }}</li>
      {% endfor %}
      {{user}}
    </ul>
    {% endblock %}
  </body>
</html>

revision_v2/mysite/food/templates/food/item-delete.html
<form method="post">
  {% csrf_token %}
  <h1>are you sure you want to delete {{item.item_name}}</h1>
  <button type="submit">confirm</button>
</form>

revision_v2/mysite/food/templates/food/item-form.html
<form method="POST">
   {% csrf_token %}
   {{form}}
   <button type="submit">Save</button>
</form>